/*
 Navicat Premium Data Transfer

 Source Server         : MacBookAir
 Source Server Type    : MySQL
 Source Server Version : 80026
 Source Host           : localhost:3306
 Source Schema         : lesson

 Target Server Type    : MySQL
 Target Server Version : 80026
 File Encoding         : 65001

 Date: 28/02/2022 18:54:40
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for department
-- ----------------------------
DROP TABLE IF EXISTS `department`;
CREATE TABLE `department` (
  `name` varchar(255) NOT NULL,
  `fisrt_department` varchar(255) DEFAULT NULL,
  `stu_number` int DEFAULT NULL,
  `admin_account` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----------------------------
-- Table structure for lessons
-- ----------------------------
DROP TABLE IF EXISTS `lessons`;
CREATE TABLE `lessons` (
  `markid` int NOT NULL AUTO_INCREMENT,
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `week` int NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`markid`)
) ENGINE=InnoDB AUTO_INCREMENT=2157 DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for profile
-- ----------------------------
DROP TABLE IF EXISTS `profile`;
CREATE TABLE `profile` (
  `name` varchar(255) NOT NULL,
  `id` int NOT NULL,
  `first_department` varchar(255) DEFAULT NULL,
  `second_department` varchar(255) DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `has_work` int unsigned DEFAULT '0',
  `free1_1` varbinary(25) DEFAULT NULL,
  `free1_2` varbinary(25) DEFAULT NULL,
  `free1_3` varbinary(25) DEFAULT NULL,
  `free1_4` varbinary(25) DEFAULT NULL,
  `free1_5` varbinary(25) DEFAULT NULL,
  `free1_6` varbinary(25) DEFAULT NULL,
  `free2_1` varbinary(25) DEFAULT NULL,
  `free2_2` varbinary(25) DEFAULT NULL,
  `free2_3` varbinary(25) DEFAULT NULL,
  `free2_4` varbinary(25) DEFAULT NULL,
  `free2_5` varbinary(25) DEFAULT NULL,
  `free2_6` varbinary(25) DEFAULT NULL,
  `free3_1` varbinary(25) DEFAULT NULL,
  `free3_2` varbinary(25) DEFAULT NULL,
  `free3_3` varbinary(25) DEFAULT NULL,
  `free3_4` varbinary(25) DEFAULT NULL,
  `free3_5` varbinary(25) DEFAULT NULL,
  `free3_6` varbinary(25) DEFAULT NULL,
  `free4_1` varbinary(25) DEFAULT NULL,
  `free4_2` varbinary(25) DEFAULT NULL,
  `free4_3` varbinary(25) DEFAULT NULL,
  `free4_4` varbinary(25) DEFAULT NULL,
  `free4_5` varbinary(25) DEFAULT NULL,
  `free4_6` varbinary(25) DEFAULT NULL,
  `free5_1` varbinary(25) DEFAULT NULL,
  `free5_2` varbinary(25) DEFAULT NULL,
  `free5_3` varbinary(25) DEFAULT NULL,
  `free5_4` varbinary(25) DEFAULT NULL,
  `free5_5` varbinary(25) DEFAULT NULL,
  `free5_6` varbinary(25) DEFAULT NULL,
  `free6_1` varbinary(25) DEFAULT NULL,
  `free6_2` varbinary(25) DEFAULT NULL,
  `free6_3` varbinary(25) DEFAULT NULL,
  `free6_4` varbinary(25) DEFAULT NULL,
  `free6_5` varbinary(25) DEFAULT NULL,
  `free6_6` varbinary(25) DEFAULT NULL,
  `free7_1` varbinary(25) DEFAULT NULL,
  `free7_2` varbinary(25) DEFAULT NULL,
  `free7_3` varbinary(25) DEFAULT NULL,
  `free7_4` varbinary(25) DEFAULT NULL,
  `free7_5` varbinary(25) DEFAULT NULL,
  `free7_6` varbinary(25) DEFAULT NULL,
  `notice` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----------------------------
-- Table structure for week1
-- ----------------------------
DROP TABLE IF EXISTS `week1`;
CREATE TABLE `week1` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week10
-- ----------------------------
DROP TABLE IF EXISTS `week10`;
CREATE TABLE `week10` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week11
-- ----------------------------
DROP TABLE IF EXISTS `week11`;
CREATE TABLE `week11` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week12
-- ----------------------------
DROP TABLE IF EXISTS `week12`;
CREATE TABLE `week12` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week13
-- ----------------------------
DROP TABLE IF EXISTS `week13`;
CREATE TABLE `week13` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week14
-- ----------------------------
DROP TABLE IF EXISTS `week14`;
CREATE TABLE `week14` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week15
-- ----------------------------
DROP TABLE IF EXISTS `week15`;
CREATE TABLE `week15` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week16
-- ----------------------------
DROP TABLE IF EXISTS `week16`;
CREATE TABLE `week16` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week17
-- ----------------------------
DROP TABLE IF EXISTS `week17`;
CREATE TABLE `week17` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week18
-- ----------------------------
DROP TABLE IF EXISTS `week18`;
CREATE TABLE `week18` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week19
-- ----------------------------
DROP TABLE IF EXISTS `week19`;
CREATE TABLE `week19` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week2
-- ----------------------------
DROP TABLE IF EXISTS `week2`;
CREATE TABLE `week2` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week20
-- ----------------------------
DROP TABLE IF EXISTS `week20`;
CREATE TABLE `week20` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week21
-- ----------------------------
DROP TABLE IF EXISTS `week21`;
CREATE TABLE `week21` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week22
-- ----------------------------
DROP TABLE IF EXISTS `week22`;
CREATE TABLE `week22` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week23
-- ----------------------------
DROP TABLE IF EXISTS `week23`;
CREATE TABLE `week23` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week24
-- ----------------------------
DROP TABLE IF EXISTS `week24`;
CREATE TABLE `week24` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week3
-- ----------------------------
DROP TABLE IF EXISTS `week3`;
CREATE TABLE `week3` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week4
-- ----------------------------
DROP TABLE IF EXISTS `week4`;
CREATE TABLE `week4` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week5
-- ----------------------------
DROP TABLE IF EXISTS `week5`;
CREATE TABLE `week5` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week6
-- ----------------------------
DROP TABLE IF EXISTS `week6`;
CREATE TABLE `week6` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week7
-- ----------------------------
DROP TABLE IF EXISTS `week7`;
CREATE TABLE `week7` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week8
-- ----------------------------
DROP TABLE IF EXISTS `week8`;
CREATE TABLE `week8` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

-- ----------------------------
-- Table structure for week9
-- ----------------------------
DROP TABLE IF EXISTS `week9`;
CREATE TABLE `week9` (
  `stuid` int NOT NULL,
  `name` varchar(255) NOT NULL,
  `d1_1` bit(1) DEFAULT NULL,
  `d1_2` bit(1) DEFAULT NULL,
  `d1_3` bit(1) DEFAULT NULL,
  `d1_4` bit(1) DEFAULT NULL,
  `d1_5` bit(1) DEFAULT NULL,
  `d1_6` bit(1) DEFAULT NULL,
  `d1_7` bit(1) DEFAULT NULL,
  `d2_1` bit(1) DEFAULT NULL,
  `d2_2` bit(1) DEFAULT NULL,
  `d2_3` bit(1) DEFAULT NULL,
  `d2_4` bit(1) DEFAULT NULL,
  `d2_5` bit(1) DEFAULT NULL,
  `d2_6` bit(1) DEFAULT NULL,
  `d2_7` bit(1) DEFAULT NULL,
  `d3_1` bit(1) DEFAULT NULL,
  `d3_2` bit(1) DEFAULT NULL,
  `d3_3` bit(1) DEFAULT NULL,
  `d3_4` bit(1) DEFAULT NULL,
  `d3_5` bit(1) DEFAULT NULL,
  `d3_6` bit(1) DEFAULT NULL,
  `d3_7` bit(1) DEFAULT NULL,
  `d4_1` bit(1) DEFAULT NULL,
  `d4_2` bit(1) DEFAULT NULL,
  `d4_3` bit(1) DEFAULT NULL,
  `d4_4` bit(1) DEFAULT NULL,
  `d4_5` bit(1) DEFAULT NULL,
  `d4_6` bit(1) DEFAULT NULL,
  `d4_7` bit(1) DEFAULT NULL,
  `d5_1` bit(1) DEFAULT NULL,
  `d5_2` bit(1) DEFAULT NULL,
  `d5_3` bit(1) DEFAULT NULL,
  `d5_4` bit(1) DEFAULT NULL,
  `d5_5` bit(1) DEFAULT NULL,
  `d5_6` bit(1) DEFAULT NULL,
  `d5_7` bit(1) DEFAULT NULL,
  `d6_1` bit(1) DEFAULT NULL,
  `d6_2` bit(1) DEFAULT NULL,
  `d6_3` bit(1) DEFAULT NULL,
  `d6_4` bit(1) DEFAULT NULL,
  `d6_5` bit(1) DEFAULT NULL,
  `d6_6` bit(1) DEFAULT NULL,
  `d6_7` bit(1) DEFAULT NULL,
  `d7_1` bit(1) DEFAULT NULL,
  `d7_2` bit(1) DEFAULT NULL,
  `d7_3` bit(1) DEFAULT NULL,
  `d7_4` bit(1) DEFAULT NULL,
  `d7_5` bit(1) DEFAULT NULL,
  `d7_6` bit(1) DEFAULT NULL,
  `d7_7` bit(1) DEFAULT NULL,
  PRIMARY KEY (`stuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

SET FOREIGN_KEY_CHECKS = 1;
